repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    -   id: double-quote-string-fixer
    -   id: end-of-file-fixer
    -   id: fix-encoding-pragma
    -   id: mixed-line-ending
    -   id: trailing-whitespace
        exclude: >-
            (?x)^(
                tests/.*.*out|
                tests/.*.in$
            )$

-   repo: https://github.com/PyCQA/pydocstyle
    rev: 5.0.2
    hooks:
    -   id: pydocstyle
        exclude: &exclude_files >
            (?x)^(
                aiida_quantumespresso/calculations/pwimmigrant.*|
                aiida_quantumespresso/parsers/.*|
                docs/.*|
                tests/.*(?<!\.py)$
            )$
        args: ['--ignore=D104,D202,D203,D213']

-   repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.30.0
    hooks:
    -   id: yapf
        name: yapf
        types: [python]
        args: ['-i']

-   repo: https://github.com/PyCQA/pylint
    rev: pylint-2.6.0
    hooks:
    -   id: pylint
        language: system
        exclude: *exclude_files

-   repo: local
    hooks:
    -   id: version-number
        name: Check consistency in version number
        entry: python ./utils/validate_version_number.py
        args: ['version']
        language: system
        files: >-
            (?x)^(
                setup.json|
                aiida_quantumespresso/__init__.py|
                ./utils/validate_version_number.py|
            )$
        pass_filenames: false
